services:
  microblog:
    build: .
    ports: 
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:devpassword@microblog-postgres/microblog"
  microblog-postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_DB: "microblog"
