[project]
name = "flask-tutorial"
version = "0.1.0"
description = "Miguel Grinberg flask tutorial"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "python-dotenv>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "taskipy>=1.14.0",
]

[tool.taskipy.tasks]
dev = "flask run --debug"
